apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: delete-hooks-job
        image: "{{ .Values.images.hook_manager }}"
        command: ["/delete_webhooks.sh"]
        env:
        - name: BOT_USER_ID
          value: "{{ .Values.githubBotAccount }}"
        - name: REPOS_TO_HOOK
          value: "( {{ .Values.repos }} )"
        - name: AUTH_ID
          valueFrom:
            secretKeyRef:
              name: hookmanager-cred
              key: auth_id
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hookmanager-cred
              key: auth_token
        volumeMounts:
        - name: hooks
          mountPath: /etc/webhooks
          readOnly: true
        
      volumes:
      - name: hooks
        secret:
          secretName: created_hooks