
apiVersion: v1
metadata:
  name: '{{ template "fullname" . }}.lego'
data:
  # modify this to specify your address
  lego.email: "john.felten@gmail.com"
  # configre letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap