apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "splice" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "splice" . }}
spec:
  replicas: {{ .Values.splice.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ template "splice" . }}"
        app: {{ template "splice" . }}
    spec:
      containers:
      - name: "{{ template "splice" . }}"
        image: "{{ .Values.images.splice }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        args:
        - -log-json
        env:
        - name: LINE_IMAGE
          value: "{{ .Values.images.line }}"
        - name: DRY_RUN
          value: "false"
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
