# Default values for prow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

githubBotAccount: samsungbot
githubHookConsumerAddress: "https://prow.cnct.io/hook"
jenkinsaddress: ""
repos: 
  - samsung-cnct/prow-chart
  - samsung-cnct/lbex 
  - samsung-cnct/documentation 
  - samsung-cnct/k2 
  - samsung-cnct/terraform-provider-distroimage 
  - samsung-cnct/flipbit
  - samsung-cnct/gci-iptables-conf-agent
  - samsung-cnct/k2-tools
  - samsung-cnct/kraken-ci-jobs
  - samsung-cnct/k8s-on-joyent
  - samsung-cnct/drunkensmee
  - samsung-cnct/cassandra-container
  - samsung-cnct/teraform-provider-coreosbox
  - samsung-cnct/k2cli
  - samsung-cnct/kraken-services
  - samsung-cnct/careen-docker
  - samsung-cnct/technical-onboarding
  - samsung-cnct/team-opensource
  - samsung-cnct/nc-pod
  - samsung-cnct/docs-ghp-staging
  - samsung-cnct/samsung-cnct.github.io
  - samsung-cnct/homebrew-terraform-provider-coreosbox
  - samsung-cnct/mass-ansible-playbook
  - samsung-cnct/terraform-provider-execute
  - samsung-cnct/logrotate
  - samsung-cnct/terraform-provider-coreos
  - samsung-cnct/careen
  - samsung-cnct/shared-logging-directory
  - samsung-cnct/k2-logging-fluentd-daemonset
  - samsung-cnct/gci-dnsmasq
  - samsung-cnct/vault
  - samsung-cnct/kraken
  - samsung-cnct/consul

images:
  crier: jfelten/crier:latest
  deck: jfelten/deck:latest
  hook: jfelten/hook:latest
  hook_manager: jfelten/hook_manager:latest
  horologium: jfelten/horologium:latest
  lego: jetstack/kube-lego:0.1.3
  line: jfelten/line:latest
  marque: jfelten/marque:latest
  sinker: jfelten/sinker:latest
  splice: jfelten/splice:latest
  tot: jfelten/tot:latest
  
  pullPolicy: Always

crier:
  replicaCount: 1
  service:
    name: crier
    type: ClusterIP
    externalPort: 8888
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
deck:
  replicaCount: 3
  service:
    name: crier
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

hook:
  replicaCount: 1
  service:
    name: hook
    type: ClusterIP
    externalPort: 8888
    internalPort: 8888
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

horologium:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

marque:
  replicaCount: 1
  service:
    name: marque
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

sinker:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

splice:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

tot:
  persistence: 
    Enabled: false
    #StorageClass: generic
    AccessMode: ReadWriteOnce
    Size: 1Gi
  replicaCount: 1
  service:
    name: tot
    type: ClusterIP
    externalPort: 8888
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

